### ISSUE TITLE
How to search from all history?

### ISSUE THREAD

**Issue by Explorare** [MrSaints/historyx#6]
How to search from all history but not just one day?

Is it possible to support more flags? Such as regular expressions? Or "before" / "after" / "during".

**Comment by MrSaints** [comment]
@Explorare Yea, I need to improve the search functionality, but for now, to search from all history, just de-select the currently selected day. That should make it show all, and from there, you can search for all.

**Comment by MrSaints** [comment]
Closing as this issue is stale, and I'm working on v3 https://github.com/MrSaints/historyx/tree/v3
